### PR TITLE
Another take on the NC probe

### PR DESCRIPTION
**Pull request by sporkus**
I tried the BFP version and it worked fantastic, but the assembly was a bit difficult and I think the hole size for the M3 screw was a bit too loose. 

I made this one from scratch. The idea is exactly the same as yours, except:

- Use a heatset for the M3 screw. Assembly is easy, just thread the wire out of the hole and jam the heatset in. Electrical connection doesn't depend on capturing the wire by screwing into plastic anymore.
- The wire for the pin goes straight up and makes the 90 turn at the magnet surface. I though it was easier to assemble.

Not sure what to name things, so I labeled everything as NC probe.
I added STEP file in the CAD folder, STLs in STL folder, and cutouts in the pictures folder.

 I also included test data at room temp and print temp with 5k samples each. The print temp test condition isn't well controlled, and showed clear thermal expansion trend throughout the test.

### CODE REVIEW

**Comment by sporkus** [comment]
p.s the magnets I bought were undersized at 2.65mm thick, so there are stls for both 2.6mm and 3.0mm magnets.

**Comment by majarspeed** [comment]
The issue that I see is that there is no slack for the pin wire to move freely. it has to be taking it from the wire wrap. I think this may cause issues.

**Comment by jlas1** [comment]
Sometimes, there are many solutions for the same issues, i too am not very comfortable with the pin wire connection.
What i propose is that we create a usermods directory and store this alternate take on the NC probe there, that way it will be easy to find, and may be useful to someone that feels that the current version has issues.

**Comment by majarspeed** [comment]
If you can ping me on discord Dustinspeed We can chat. I would like to know how its going and talk about moving it into a usermod folder.

**Comment by sporkus** [comment]
You guys made a good point about the wire slack. However, the actual pin movement is so little that it might not really matter. I'm using 0.05mm retract between samples.  But there's no way to know if it is more/less reliable unless it's been tested long term with different users/wire types.

I've moved all my additions to a usermod folder to keep the repo organized, so it should be a clean merge.

**Pull request closed without merging**
